// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3qYUZt4jWtpA-xlB8ipRCDyo6IVlkAQ',
    appId: '1:248895789056:web:9ce40596803b94275ca0e5',
    messagingSenderId: '248895789056',
    projectId: 'myflutterapp-131b8',
    authDomain: 'myflutterapp-131b8.firebaseapp.com',
    storageBucket: 'myflutterapp-131b8.firebasestorage.app',
    measurementId: 'G-MCN8C7VCCG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsQio6T4gyKS37Vv-9PAt_hjIROEqWQZU',
    appId: '1:248895789056:ios:a43a982b55e378445ca0e5',
    messagingSenderId: '248895789056',
    projectId: 'myflutterapp-131b8',
    storageBucket: 'myflutterapp-131b8.firebasestorage.app',
    iosBundleId: 'com.example.myflutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsQio6T4gyKS37Vv-9PAt_hjIROEqWQZU',
    appId: '1:248895789056:ios:a43a982b55e378445ca0e5',
    messagingSenderId: '248895789056',
    projectId: 'myflutterapp-131b8',
    storageBucket: 'myflutterapp-131b8.firebasestorage.app',
    iosBundleId: 'com.example.myflutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH3qYUZt4jWtpA-xlB8ipRCDyo6IVlkAQ',
    appId: '1:248895789056:web:4192c25a10178b855ca0e5',
    messagingSenderId: '248895789056',
    projectId: 'myflutterapp-131b8',
    authDomain: 'myflutterapp-131b8.firebaseapp.com',
    storageBucket: 'myflutterapp-131b8.firebasestorage.app',
    measurementId: 'G-CSDKYCD8TT',
  );

}